# Generated by Django 5.0 on 2024-01-24 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_string",
                    models.CharField(db_comment="source string", max_length=3000),
                ),
                (
                    "target_string",
                    models.CharField(db_comment="target string", max_length=3000),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="created at"),
                ),
                ("deleted", models.BooleanField(db_comment="deleted", default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(db_comment="deleted at", null=True),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_string",
                    models.CharField(db_comment="source string", max_length=3000),
                ),
                (
                    "target_string",
                    models.CharField(db_comment="target string", max_length=3000),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="created at"),
                ),
                ("deleted", models.BooleanField(db_comment="deleted", default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(db_comment="deleted at", null=True),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_string",
                    models.CharField(db_comment="source string", max_length=3000),
                ),
                (
                    "target_string",
                    models.CharField(db_comment="target string", max_length=3000),
                ),
                ("rating", models.IntegerField(db_comment="rating")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_comment="created at"),
                ),
                ("deleted", models.BooleanField(db_comment="deleted", default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(db_comment="deleted at", null=True),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
