# Generated by Django 5.0 on 2024-01-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_userprofile_userid_delete_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="userid", new_name="user",
        ),
    ]
